[[libinchi]]
arch = "aarch64"
git-tree-sha1 = "d12d90b6bab6241be5e599d8e418ae6507afaea7"
os = "macos"

    [[libinchi.download]]
    sha256 = "4ae6e138aa002a41bd2a19e4ef4e7ea06a992520a181210975801a897d58bc0b"
    url = "https://github.com/JuliaBinaryWrappers/libinchi_jll.jl/releases/download/libinchi-v1.6.0+0/libinchi.v1.6.0.aarch64-apple-darwin.tar.gz"
[[libinchi]]
arch = "aarch64"
git-tree-sha1 = "e5d74fff1398138bd657b08062893dc33cfa3f31"
libc = "glibc"
os = "linux"

    [[libinchi.download]]
    sha256 = "57257b84c7fb51f11ec20ef38b0ee5410e47c8c0f600935276bd538a45d1e9b9"
    url = "https://github.com/JuliaBinaryWrappers/libinchi_jll.jl/releases/download/libinchi-v1.6.0+0/libinchi.v1.6.0.aarch64-linux-gnu.tar.gz"
[[libinchi]]
arch = "aarch64"
git-tree-sha1 = "aa7a2135af13f9bf4e76c22e44bc6f8d3607a25f"
libc = "musl"
os = "linux"

    [[libinchi.download]]
    sha256 = "9c9d0c4016c3b53982be6b5f752b4a1f8edd2421b68673c07119cdd890bfba94"
    url = "https://github.com/JuliaBinaryWrappers/libinchi_jll.jl/releases/download/libinchi-v1.6.0+0/libinchi.v1.6.0.aarch64-linux-musl.tar.gz"
[[libinchi]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "67c8a7c6bed3ed51da9ce8a00fa482e886ab5bc6"
libc = "glibc"
os = "linux"

    [[libinchi.download]]
    sha256 = "55f10f75c3093dd0569507d60bd6dd34b1c6cec98763add35357d0013b451d9a"
    url = "https://github.com/JuliaBinaryWrappers/libinchi_jll.jl/releases/download/libinchi-v1.6.0+0/libinchi.v1.6.0.armv6l-linux-gnueabihf.tar.gz"
[[libinchi]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1514424a69ef05bf91a5cd713791d9f9b05535f1"
libc = "musl"
os = "linux"

    [[libinchi.download]]
    sha256 = "e9f50124b49a8c10b5759156fbeedf29025e25ac43c1b147dade10b3723b6b35"
    url = "https://github.com/JuliaBinaryWrappers/libinchi_jll.jl/releases/download/libinchi-v1.6.0+0/libinchi.v1.6.0.armv6l-linux-musleabihf.tar.gz"
[[libinchi]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d8c4f04257b05d270624de5ada0d870842f93a02"
libc = "glibc"
os = "linux"

    [[libinchi.download]]
    sha256 = "40a2dd72e2f4a91c68d5793e760d2ba8519956802e3ca5f757fdaf811d44b657"
    url = "https://github.com/JuliaBinaryWrappers/libinchi_jll.jl/releases/download/libinchi-v1.6.0+0/libinchi.v1.6.0.armv7l-linux-gnueabihf.tar.gz"
[[libinchi]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "23d27da8b9314a4c52be0c431c79af320da4ec38"
libc = "musl"
os = "linux"

    [[libinchi.download]]
    sha256 = "31c803d572e9b441ea080edc4eb1839850aa44868ce409693a0903d8e178ae75"
    url = "https://github.com/JuliaBinaryWrappers/libinchi_jll.jl/releases/download/libinchi-v1.6.0+0/libinchi.v1.6.0.armv7l-linux-musleabihf.tar.gz"
[[libinchi]]
arch = "i686"
git-tree-sha1 = "1be6e059e312c99733d78bd15df334ea0165cf53"
libc = "glibc"
os = "linux"

    [[libinchi.download]]
    sha256 = "32042094860c492f0685a825a41c6fd0820171b91330bcaf6c9595395b4fe608"
    url = "https://github.com/JuliaBinaryWrappers/libinchi_jll.jl/releases/download/libinchi-v1.6.0+0/libinchi.v1.6.0.i686-linux-gnu.tar.gz"
[[libinchi]]
arch = "i686"
git-tree-sha1 = "fc30ecd8e2a5d9ed2c4bc4edfec7c4378f77348b"
libc = "musl"
os = "linux"

    [[libinchi.download]]
    sha256 = "495cb6313df182c6970bff07ff51e92c6648fa742670b108b3f59f29a439408c"
    url = "https://github.com/JuliaBinaryWrappers/libinchi_jll.jl/releases/download/libinchi-v1.6.0+0/libinchi.v1.6.0.i686-linux-musl.tar.gz"
[[libinchi]]
arch = "i686"
git-tree-sha1 = "2ed19e851982b2144d73dd4daa5254e862d6a21e"
os = "windows"

    [[libinchi.download]]
    sha256 = "3d368bb41dbbafa1822a62393cac6b08ca7582a9e2138da7f0bda5c9cb84995a"
    url = "https://github.com/JuliaBinaryWrappers/libinchi_jll.jl/releases/download/libinchi-v1.6.0+0/libinchi.v1.6.0.i686-w64-mingw32.tar.gz"
[[libinchi]]
arch = "powerpc64le"
git-tree-sha1 = "fab0830327eedc7ea51ff463cc28ab12308ad4a2"
libc = "glibc"
os = "linux"

    [[libinchi.download]]
    sha256 = "b7d161784cf804f34b42de64b15677d388bd6d300328d57a7ad2ed3099a305d3"
    url = "https://github.com/JuliaBinaryWrappers/libinchi_jll.jl/releases/download/libinchi-v1.6.0+0/libinchi.v1.6.0.powerpc64le-linux-gnu.tar.gz"
[[libinchi]]
arch = "x86_64"
git-tree-sha1 = "c3449de3970a192ca9d1e25c3807c6aaaa176aa0"
os = "macos"

    [[libinchi.download]]
    sha256 = "2eb89a00d5eaec7cb8190af6832d42cb971d2b589a4ee1136c87bab10f7b90ee"
    url = "https://github.com/JuliaBinaryWrappers/libinchi_jll.jl/releases/download/libinchi-v1.6.0+0/libinchi.v1.6.0.x86_64-apple-darwin.tar.gz"
[[libinchi]]
arch = "x86_64"
git-tree-sha1 = "9de77de71df89ddbe8da148757f28bab19ddda2c"
libc = "glibc"
os = "linux"

    [[libinchi.download]]
    sha256 = "b9d41d88e54b3766aff422ca6c4147f4e5ff7846f005af379221cc38b72a50d6"
    url = "https://github.com/JuliaBinaryWrappers/libinchi_jll.jl/releases/download/libinchi-v1.6.0+0/libinchi.v1.6.0.x86_64-linux-gnu.tar.gz"
[[libinchi]]
arch = "x86_64"
git-tree-sha1 = "789bd203cf96a7d1dd4de9b43e914f0c3ca714c8"
libc = "musl"
os = "linux"

    [[libinchi.download]]
    sha256 = "86574f1c2008e3575abaf83a92092f81dabaccf937647b486dae566a3e5955a5"
    url = "https://github.com/JuliaBinaryWrappers/libinchi_jll.jl/releases/download/libinchi-v1.6.0+0/libinchi.v1.6.0.x86_64-linux-musl.tar.gz"
[[libinchi]]
arch = "x86_64"
git-tree-sha1 = "d87aa9bd36b314e3698a2a6ebfabaf91d17fa70f"
os = "freebsd"

    [[libinchi.download]]
    sha256 = "0ffde7e3a158a783ce8601ce9950e195e0323ce128f706b46dad3f0db5145280"
    url = "https://github.com/JuliaBinaryWrappers/libinchi_jll.jl/releases/download/libinchi-v1.6.0+0/libinchi.v1.6.0.x86_64-unknown-freebsd.tar.gz"
[[libinchi]]
arch = "x86_64"
git-tree-sha1 = "c3d548e802545ed1a95eac4d29ebdeb56fa6d8e4"
os = "windows"

    [[libinchi.download]]
    sha256 = "758589f09cecff5ee74774627c34f9b421cd47aa2785f18baa46f720ba52851e"
    url = "https://github.com/JuliaBinaryWrappers/libinchi_jll.jl/releases/download/libinchi-v1.6.0+0/libinchi.v1.6.0.x86_64-w64-mingw32.tar.gz"
